-- Active: 1782312708035@@gateway01.ap-southeast-1.prod.aws.tidbcloud.com@4000@portofolio_db
-- Portfolio Database Schema
-- Rename this file to: DB_<NIM>_<NAMA>.sql before submission
-- Compatible with TiDB (MySQL syntax)

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(80) NOT NULL UNIQUE,
  `password` VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS `profiles` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(120),
  `tagline` VARCHAR(200),
  `bio` TEXT,
  `about` TEXT,
  `email` VARCHAR(120),
  `location` VARCHAR(120),
  `photo_url` VARCHAR(500),
  `years_exp` INT DEFAULT 0,
  `organizations` INT DEFAULT 0,
  `projects_done` INT DEFAULT 0,
  `education` TEXT
);

CREATE TABLE IF NOT EXISTS `skills` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `type` VARCHAR(20) DEFAULT 'technical',
  `level` INT DEFAULT 80,
  `description` VARCHAR(300)
);

CREATE TABLE IF NOT EXISTS `experience` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(120),
  `company` VARCHAR(120),
  `period` VARCHAR(80),
  `description` TEXT
);

CREATE TABLE IF NOT EXISTS `projects` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(120),
  `category` VARCHAR(80),
  `description` TEXT,
  `image_url` VARCHAR(500),
  `link` VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS `contacts` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(120),
  `email` VARCHAR(120),
  `message` TEXT,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Default admin user (password: admin123)
INSERT IGNORE INTO `users` (`username`, `password`) VALUES
('admin', 'pbkdf2:sha256:600000$admin123hash');
-- Note: actual hash will be generated by Flask on first run via _seed_admin()
